Mersenne Twister as RNG

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6413,6 +6413,77 @@ else
 echo "${ECHO_T}not found" >&6; };
 fi
 
+{ echo "$as_me:$LINENO: checking for gsl_blas_dgemm in -lgsl" >&5
+echo $ECHO_N "checking for gsl_blas_dgemm in -lgsl... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gsl_gsl_blas_dgemm+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgsl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gsl_blas_dgemm ();
+int
+main ()
+{
+return gsl_blas_dgemm ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_gsl_gsl_blas_dgemm=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_gsl_gsl_blas_dgemm=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gsl_gsl_blas_dgemm" >&5
+echo "${ECHO_T}$ac_cv_lib_gsl_gsl_blas_dgemm" >&6; }
+if test $ac_cv_lib_gsl_gsl_blas_dgemm = yes; then
+  LFLAGS="$LDFLAGS -lgsl";
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_MERSENNE_TWISTER
+_ACEOF
+
+fi
+
+
 # We use auto for data librarian to avoid breaking the rule that autoconf
 # should use the same defaults as the manual configuration, but all platforms
 # that support autoconf also support DLB, so the automatic choice is always yes.
